### ISSUE TITLE
doesn't seem to be working

### ISSUE THREAD

**Issue by DataGreed** [LukeDowell/flash-chords#24]
Doesn't seem to detect any midi input and I cannot find any way to change select the midi input device :(

**Comment by LukeDowell** [comment]
Hey thanks for the issue! I am going to push some changes that will allow users to see a drop down with all the currently detected MIDI devices. I'll close this issue when it's complete.

Currently, the application just tries to use the very first MIDI device it finds on refresh. Also, you'll need to be sure that you are using a chromium-based browser, Brave and Chrome work for me.

More UX / helpful messages around this kind of stuff is definitely needed.

**Comment by LukeDowell** [comment]
Surely my worst PR response time ever; sorry! 

There is now a drop down to select your MIDI device in the nav bar. Still far from ideal, but at least it's a little better.
